version: '3'

services:
  ros:
    build: .
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /home/$USER/:/home/$USER/
    environment:
      DISPLAY: $DISPLAY
      QT_GRAPHICSSYSTEM: native
    user: $USER_ID
    devices: 
      - /dev/dri:/dev/dri
    network_mode: host
